isoMetadata:
  #01_basisangaben
  title:
    # Administrator: "isoMetadata/title.admin.md"
    # QualityAssurance: "isoMetadata/title.qs.md"
    # DataOwner: "isoMetadata/title.dhs.md"
    #Editor: "01_basisangaben/title.redakteur.md"
    default: "01_basisangaben/title.md"
  description:
    default: "01_basisangaben/description.md"
  keywords:
    default: "01_basisangaben/keywords.md"
  preview:
    default: "01_basisangaben/preview.md"
  pointsOfContact:
    default: "01_basisangaben/pointsOfContact.md"
  #02_einordnung
  metadataProfile:
    default: "02_einordnung/metadataType.md"
  highValueDataCategory:
    default: "02_einordnung/highValueDataset.md"
  inspireTheme:
    default: "02_einordnung/inspireAnnexTheme.md"
  inspireFormatName:
    default: "02_einordnung/inspireSchemaName.md"
  inspireAnnexVersion:
    default: "02_einordnung/inspireSchemaVersion.md"
  valid:
    default: "02_einordnung/inspireValid.md"
  termsOfUseId:
    default: "02_einordnung/termsOfUseId.md"
  termsOfUseSource:
    default: "02_einordnung/termsOfUseSource.md"
  topicCategory:
    default: "02_einordnung/topicCategory.md"
  #03_zeitlicheUndRaeumlicheAngaben
  created:
    default: "03_zeitlicheUndRaeumlicheAngaben/created.md"
  published:
    default: "03_zeitlicheUndRaeumlicheAngaben/published.md"
  maintenanceFrequency:
    default: "03_zeitlicheUndRaeumlicheAngaben/maintenanceFrequency.md"
  modified:
    default: "03_zeitlicheUndRaeumlicheAngaben/modified.md"
  validFrom:
    default: "03_zeitlicheUndRaeumlicheAngaben/validFrom.md"
  crs:
    default: "03_zeitlicheUndRaeumlicheAngaben/crs.md"
  extent:
    default: "03_zeitlicheUndRaeumlicheAngaben/extent.md"
  resolutions:
    default: "03_zeitlicheUndRaeumlicheAngaben/resolutions.md"
  scale:
    default: "03_zeitlicheUndRaeumlicheAngaben/resolutions.md"
  spatialRepresentationTypes:
    default: "03_zeitlicheUndRaeumlicheAngaben/spatialRepresentationType.md"
  #04_weitereAngaben
  contentDescription:
    default: "04_weitereAngaben/contentDescription.md"
  technicalDescription:
    default: "04_weitereAngaben/technicalDescription.md"
  lineage:
    default: "04_weitereAngaben/lineage.md"
  contentDescriptions:
    default: "04_weitereAngaben/furtherInformation.md"
  #05_dienste
  services:
    type:
      default: "05_dienste/serviceType.md"
    title:
      default: "05_dienste/serviceTitle.md"
    shortDescription:
      default: "05_dienste/serviceShortDescription.md"
    workspace:
      default: "05_dienste/serviceIdentificator.md"
    preview:
      default: "05_dienste/servicePreview.md"
    legendImage:
      default: "05_dienste/serviceLegendImage.md"
    featureTypes:
      default: "05_dienste/featureType.md"
      title:
        default: "05_dienste/featureTypeTitle.md"
      name:
        default: "05_dienste/featureTypeName.md"
      shortDescription:
        default: "05_dienste/featureTypeShortDescription.md"
      columns:
        default: "05_dienste/featureTypeColumn.md"
        name:
          default: "05_dienste/featureTypeColumnName.md"
        alias:
          default: "05_dienste/featureTypeColumnAlias.md"
        type:
          default: "05_dienste/featureTypeColumnType.md"
clientMetadata:
  #02_einordnung
  privacy:
    default: "02_einordnung/privacy.md"
  #01_basisangaben
  comments:
    default: "01_basisangaben/comments.md"
  #05_dienste
  layers:
    default: "05_dienste/layers.md"
    title:
      default: "05_dienste/layerTitle.md"
    name:
      default: "05_dienste/layerName.md"
    styleTitle:
      default: "05_dienste/layerStyleTitle.md"
    styleName:
      default: "05_dienste/layerStyleName.md"
    legendImage:
      default: "05_dienste/layerLegendImage.md"
    shortDescription:
      default: "05_dienste/layerShortDescription.md"
    datasource:
      default: "05_dienste/layerDatasource.md"
    secondaryDatasource:
      default: "05_dienste/layerSecondaryDatasource.md"

technicalMetadata:
  #03_zeitlicheUndRaeumlicheAngaben
  deliveredCrs:
    default: "03_zeitlicheUndRaeumlicheAngaben/deliveredCrs.md"
