isoMetadata:
  title:
    # Administrator: "isoMetadata/title.admin.md"
    # QualityAssurance: "isoMetadata/title.qs.md"
    # DataOwner: "isoMetadata/title.dhs.md"
    Editor: "isoMetadata/title.redakteur.md"
    default: "isoMetadata/title.md"
  description:
    default: "isoMetadata/description.md"
  keywords:
    default: "isoMetadata/keywords.md"
  preview:
    default: "isoMetadata/preview.md"
  pointsOfContact:
    default: "isoMetadata/pointsOfContact.md"
  metadataProfile:
    default: "isoMetadata/metadataProfile.md"
  highValueDataCategory:
    default: "isoMetadata/highValueDataset.md"
  inspireTheme:
    default: "isoMetadata/inspireTheme.md"
  inspireAnnexName:
    default: "isoMetadata/inspireAnnexName.md"
  inspireAnnexVersion:
    default: "isoMetadata/inspireAnnexVersion.md"
  termsOfUseId:
    default: "isoMetadata/termsOfUseId.md"
  termsOfUseSource:
    default: "isoMetadata/termsOfUseSource.md"
  topicCategory:
    default: "isoMetadata/topicCategory.md"
  created:
    default: "isoMetadata/created.md"
  published:
    default: "isoMetadata/published.md"
  maintenanceFrequency:
    default: "isoMetadata/maintenanceFrequency.md"
  modified:
    default: "isoMetadata/modified.md"
  validFrom:
    default: "isoMetadata/validFrom.md"
  crs:
    default: "isoMetadata/crs.md"
  extent:
    default: "isoMetadata/extent.md"
  resolutions:
    default: "isoMetadata/resolutions.md"
  scale:
    default: "isoMetadata/resolutions.md"
  spatialRepresentationType:
    default: "isoMetadata/spatialRepresentationType.md"
  contentDescription:
    default: "isoMetadata/contentDescription.md"
  technicalDescription:
    default: "isoMetadata/technicalDescription.md"
  lineage:
    default: "isoMetadata/lineage.md"
  contentDescriptions:
    default: "isoMetadata/contentDescriptions.md"
  services:
    type:
      default: "isoMetadata/serviceType.md"
    title:
      default: "isoMetadata/serviceTitle.md"
    shortDescription:
      default: "isoMetadata/serviceShortDescription.md"
    workspace:
      default: "isoMetadata/serviceWorkspace.md"
    preview:
      default: "isoMetadata/servicePreview.md"
    legendImage:
      default: "isoMetadata/serviceLegendImage.md"
    featureTypes:
      title:
        default: "isoMetadata/featureTypeTitle.md"
      name:
        default: "isoMetadata/featureTypeName.md"
      shortDescription:
        default: "isoMetadata/featureTypeShortDescription.md"
      columns:
        name:
          default: "isoMetadata/featureTypeColumnName.md"
        alias:
          default: "isoMetadata/featureTypeColumnAlias.md"
        type:
          default: "isoMetadata/featureTypeColumnType.md"
clientMetadata:
  privacy:
    default: "clientMetadata/privacy.md"
  comments:
    default: "clientMetadata/comments.md"
  layers:
    title:
      default: "clientMetadata/layerTitle.md"
    name:
      default: "clientMetadata/layerName.md"
    styleTitle:
      default: "clientMetadata/layerStyleTitle.md"
    styleName:
      default: "clientMetadata/layerStyleName.md"
    legendImage:
      default: "clientMetadata/layerLegendImage.md"
    shortDescription:
      default: "clientMetadata/layerShortDescription.md"
    datasource:
      default: "clientMetadata/layerDatasource.md"
    secondaryDatasource:
      default: "clientMetadata/layerSecondaryDatasource.md"

technicalMetadata:
  deliveredCrs:
    default: "technicalMetadata/deliveredCrs.md"
